# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import engine_pb2 as engine__pb2


class EngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Scan = channel.unary_unary(
                '/engine.EngineService/Scan',
                request_serializer=engine__pb2.ScanRequest.SerializeToString,
                response_deserializer=engine__pb2.ScanResult.FromString,
                )
        self.Carve = channel.unary_unary(
                '/engine.EngineService/Carve',
                request_serializer=engine__pb2.CarveRequest.SerializeToString,
                response_deserializer=engine__pb2.CarveResult.FromString,
                )
        self.Hash = channel.unary_unary(
                '/engine.EngineService/Hash',
                request_serializer=engine__pb2.HashRequest.SerializeToString,
                response_deserializer=engine__pb2.HashResult.FromString,
                )
        self.Ping = channel.unary_unary(
                '/engine.EngineService/Ping',
                request_serializer=engine__pb2.Empty.SerializeToString,
                response_deserializer=engine__pb2.Pong.FromString,
                )


class EngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Scan(self, request, context):
        """Performs a scan on a data source
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Carve(self, request, context):
        """Performs file carving on a raw image or disk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hash(self, request, context):
        """Calculates hashes for a given file or block
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Checks the health/status of the engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=engine__pb2.ScanRequest.FromString,
                    response_serializer=engine__pb2.ScanResult.SerializeToString,
            ),
            'Carve': grpc.unary_unary_rpc_method_handler(
                    servicer.Carve,
                    request_deserializer=engine__pb2.CarveRequest.FromString,
                    response_serializer=engine__pb2.CarveResult.SerializeToString,
            ),
            'Hash': grpc.unary_unary_rpc_method_handler(
                    servicer.Hash,
                    request_deserializer=engine__pb2.HashRequest.FromString,
                    response_serializer=engine__pb2.HashResult.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=engine__pb2.Empty.FromString,
                    response_serializer=engine__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engine.EngineService/Scan',
            engine__pb2.ScanRequest.SerializeToString,
            engine__pb2.ScanResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Carve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engine.EngineService/Carve',
            engine__pb2.CarveRequest.SerializeToString,
            engine__pb2.CarveResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Hash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engine.EngineService/Hash',
            engine__pb2.HashRequest.SerializeToString,
            engine__pb2.HashResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engine.EngineService/Ping',
            engine__pb2.Empty.SerializeToString,
            engine__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
