// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	ScanType      string                 `protobuf:"bytes,2,opt,name=scan_type,json=scanType,proto3" json:"scan_type,omitempty"`               // "full", "quick", "custom"
	Signatures    []string               `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`                           // Optional: specific signature names to look for
	YaraRulePath  string                 `protobuf:"bytes,4,opt,name=yara_rule_path,json=yaraRulePath,proto3" json:"yara_rule_path,omitempty"` // Optional: Path to YARA rules file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ScanRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ScanRequest) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *ScanRequest) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *ScanRequest) GetYaraRulePath() string {
	if x != nil {
		return x.YaraRulePath
	}
	return ""
}

type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	FilesScanned  int64                  `protobuf:"varint,3,opt,name=files_scanned,json=filesScanned,proto3" json:"files_scanned,omitempty"`
	Matches       []*FoundItem           `protobuf:"bytes,4,rep,name=matches,proto3" json:"matches,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	YaraMatches   []*YaraMatch           `protobuf:"bytes,6,rep,name=yara_matches,json=yaraMatches,proto3" json:"yara_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScanResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScanResult) GetFilesScanned() int64 {
	if x != nil {
		return x.FilesScanned
	}
	return 0
}

func (x *ScanResult) GetMatches() []*FoundItem {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *ScanResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ScanResult) GetYaraMatches() []*YaraMatch {
	if x != nil {
		return x.YaraMatches
	}
	return nil
}

type YaraMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YaraMatch) Reset() {
	*x = YaraMatch{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YaraMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YaraMatch) ProtoMessage() {}

func (x *YaraMatch) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YaraMatch.ProtoReflect.Descriptor instead.
func (*YaraMatch) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *YaraMatch) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *YaraMatch) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *YaraMatch) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type FoundItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	SignatureName string                 `protobuf:"bytes,2,opt,name=signature_name,json=signatureName,proto3" json:"signature_name,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoundItem) Reset() {
	*x = FoundItem{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundItem) ProtoMessage() {}

func (x *FoundItem) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundItem.ProtoReflect.Descriptor instead.
func (*FoundItem) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *FoundItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FoundItem) GetSignatureName() string {
	if x != nil {
		return x.SignatureName
	}
	return ""
}

func (x *FoundItem) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CarveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	OutputDir     string                 `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	BlockSize     int64                  `protobuf:"varint,3,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"` // Default 4096
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarveRequest) Reset() {
	*x = CarveRequest{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarveRequest) ProtoMessage() {}

func (x *CarveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarveRequest.ProtoReflect.Descriptor instead.
func (*CarveRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *CarveRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *CarveRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *CarveRequest) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type CarveResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	FilesRecovered int64                  `protobuf:"varint,3,opt,name=files_recovered,json=filesRecovered,proto3" json:"files_recovered,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CarveResult) Reset() {
	*x = CarveResult{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarveResult) ProtoMessage() {}

func (x *CarveResult) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarveResult.ProtoReflect.Descriptor instead.
func (*CarveResult) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *CarveResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CarveResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CarveResult) GetFilesRecovered() int64 {
	if x != nil {
		return x.FilesRecovered
	}
	return 0
}

func (x *CarveResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Algorithms    []string               `protobuf:"bytes,2,rep,name=algorithms,proto3" json:"algorithms,omitempty"` // e.g., ["sha256", "md5"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *HashRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HashRequest) GetAlgorithms() []string {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

type HashResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Hashes        map[string]string      `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // algo -> hash_value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResult) Reset() {
	*x = HashResult{}
	mi := &file_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResult) ProtoMessage() {}

func (x *HashResult) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResult.ProtoReflect.Descriptor instead.
func (*HashResult) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

func (x *HashResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HashResult) GetHashes() map[string]string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type WalkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkRequest) Reset() {
	*x = WalkRequest{}
	mi := &file_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkRequest) ProtoMessage() {}

func (x *WalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkRequest.ProtoReflect.Descriptor instead.
func (*WalkRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *WalkRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

type WalkEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          int64                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModifiedTime  int64                  `protobuf:"varint,4,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	AccessedTime  int64                  `protobuf:"varint,5,opt,name=accessed_time,json=accessedTime,proto3" json:"accessed_time,omitempty"` // Might not be available on all OS
	CreatedTime   int64                  `protobuf:"varint,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`    // Might not be available on all OS
	IsDir         bool                   `protobuf:"varint,7,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkEntry) Reset() {
	*x = WalkEntry{}
	mi := &file_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkEntry) ProtoMessage() {}

func (x *WalkEntry) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkEntry.ProtoReflect.Descriptor instead.
func (*WalkEntry) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *WalkEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WalkEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WalkEntry) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *WalkEntry) GetModifiedTime() int64 {
	if x != nil {
		return x.ModifiedTime
	}
	return 0
}

func (x *WalkEntry) GetAccessedTime() int64 {
	if x != nil {
		return x.AccessedTime
	}
	return 0
}

func (x *WalkEntry) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *WalkEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x06engine\"\a\n" +
	"\x05Empty\"<\n" +
	"\x04Pong\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x91\x01\n" +
	"\vScanRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x1b\n" +
	"\tscan_type\x18\x02 \x01(\tR\bscanType\x12\x1e\n" +
	"\n" +
	"signatures\x18\x03 \x03(\tR\n" +
	"signatures\x12$\n" +
	"\x0eyara_rule_path\x18\x04 \x01(\tR\fyaraRulePath\"\xea\x01\n" +
	"\n" +
	"ScanResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rfiles_scanned\x18\x03 \x01(\x03R\ffilesScanned\x12+\n" +
	"\amatches\x18\x04 \x03(\v2\x11.engine.FoundItemR\amatches\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x124\n" +
	"\fyara_matches\x18\x06 \x03(\v2\x11.engine.YaraMatchR\vyaraMatches\"Y\n" +
	"\tYaraMatch\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"g\n" +
	"\tFoundItem\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12%\n" +
	"\x0esignature_name\x18\x02 \x01(\tR\rsignatureName\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"m\n" +
	"\fCarveRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x02 \x01(\tR\toutputDir\x12\x1d\n" +
	"\n" +
	"block_size\x18\x03 \x01(\x03R\tblockSize\"\x8c\x01\n" +
	"\vCarveResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12'\n" +
	"\x0ffiles_recovered\x18\x03 \x01(\x03R\x0efilesRecovered\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"J\n" +
	"\vHashRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x02 \x03(\tR\n" +
	"algorithms\"\x9c\x01\n" +
	"\n" +
	"HashResult\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x126\n" +
	"\x06hashes\x18\x02 \x03(\v2\x1e.engine.HashResult.HashesEntryR\x06hashes\x1a9\n" +
	"\vHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\vWalkRequest\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\"\xcb\x01\n" +
	"\tWalkEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x03R\x04mode\x12#\n" +
	"\rmodified_time\x18\x04 \x01(\x03R\fmodifiedTime\x12#\n" +
	"\raccessed_time\x18\x05 \x01(\x03R\faccessedTime\x12!\n" +
	"\fcreated_time\x18\x06 \x01(\x03R\vcreatedTime\x12\x15\n" +
	"\x06is_dir\x18\a \x01(\bR\x05isDir2\xfc\x01\n" +
	"\rEngineService\x12/\n" +
	"\x04Scan\x12\x13.engine.ScanRequest\x1a\x12.engine.ScanResult\x122\n" +
	"\x05Carve\x12\x14.engine.CarveRequest\x1a\x13.engine.CarveResult\x12/\n" +
	"\x04Hash\x12\x13.engine.HashRequest\x1a\x12.engine.HashResult\x12#\n" +
	"\x04Ping\x12\r.engine.Empty\x1a\f.engine.Pong\x120\n" +
	"\x04Walk\x12\x13.engine.WalkRequest\x1a\x11.engine.WalkEntry0\x01B0Z.github.com/ismailtsdln/forenscope/engine/protob\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_engine_proto_goTypes = []any{
	(*Empty)(nil),        // 0: engine.Empty
	(*Pong)(nil),         // 1: engine.Pong
	(*ScanRequest)(nil),  // 2: engine.ScanRequest
	(*ScanResult)(nil),   // 3: engine.ScanResult
	(*YaraMatch)(nil),    // 4: engine.YaraMatch
	(*FoundItem)(nil),    // 5: engine.FoundItem
	(*CarveRequest)(nil), // 6: engine.CarveRequest
	(*CarveResult)(nil),  // 7: engine.CarveResult
	(*HashRequest)(nil),  // 8: engine.HashRequest
	(*HashResult)(nil),   // 9: engine.HashResult
	(*WalkRequest)(nil),  // 10: engine.WalkRequest
	(*WalkEntry)(nil),    // 11: engine.WalkEntry
	nil,                  // 12: engine.HashResult.HashesEntry
}
var file_engine_proto_depIdxs = []int32{
	5,  // 0: engine.ScanResult.matches:type_name -> engine.FoundItem
	4,  // 1: engine.ScanResult.yara_matches:type_name -> engine.YaraMatch
	12, // 2: engine.HashResult.hashes:type_name -> engine.HashResult.HashesEntry
	2,  // 3: engine.EngineService.Scan:input_type -> engine.ScanRequest
	6,  // 4: engine.EngineService.Carve:input_type -> engine.CarveRequest
	8,  // 5: engine.EngineService.Hash:input_type -> engine.HashRequest
	0,  // 6: engine.EngineService.Ping:input_type -> engine.Empty
	10, // 7: engine.EngineService.Walk:input_type -> engine.WalkRequest
	3,  // 8: engine.EngineService.Scan:output_type -> engine.ScanResult
	7,  // 9: engine.EngineService.Carve:output_type -> engine.CarveResult
	9,  // 10: engine.EngineService.Hash:output_type -> engine.HashResult
	1,  // 11: engine.EngineService.Ping:output_type -> engine.Pong
	11, // 12: engine.EngineService.Walk:output_type -> engine.WalkEntry
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
